name: OpenDictation
options:
  bundleIdPrefix: com.opendictation
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

configs:
  Debug: debug
  "Debug (Dev)": debug
  Release: release

configFiles:
  "Debug (Dev)": Config/Debug-Dev.xcconfig
  Debug: Config/Debug.xcconfig
  Release: Config.xcconfig

settings:
  base:
    INFOPLIST_FILE: OpenDictation/App/Info.plist
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
    ENABLE_HARDENED_RUNTIME: NO
    SWIFT_VERSION: "6.0"
    SDKROOT: macosx
    ARCHS: arm64

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.4.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.8.1"
  Defaults:
    url: https://github.com/sindresorhus/Defaults
    from: "9.0.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.1.0"

targets:
  OpenDictation:
    type: application
    platform: macOS
    sources:
      - path: OpenDictation/App
        excludes:
          - Info.plist
      - path: OpenDictation/Core
      - path: OpenDictation/Views
      - path: OpenDictation/Models
      - path: OpenDictation/Extensions
        optional: true
      - path: OpenDictation/Utilities
        optional: true
      - path: OpenDictation/Resources/Sounds
        buildPhase: resources
        type: folder
      - path: OpenDictation/Resources/Models
        buildPhase: resources
        type: folder
      - path: OpenDictation/Resources/Assets.xcassets
        buildPhase: resources
      - path: OpenDictation/Resources/DMG
        buildPhase: resources
        type: folder
    settings:
      base:
        INFOPLIST_FILE: OpenDictation/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: OpenDictation/OpenDictation.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: 
          - "@executable_path/../Frameworks"
          - "@loader_path/../Frameworks"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/Frameworks"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS:
          - "$(inherited)"
          - "XCODE_BUILD"
    dependencies:
      - package: KeyboardShortcuts
      - package: Sparkle
        product: Sparkle
      - package: Defaults
      - package: LaunchAtLogin
      - framework: Frameworks/whisper.xcframework
        embed: true
    preBuildScripts: []
    postBuildScripts: []
